# Tecnicas para limpieza de datos

1. Eliminar duplicados
`drop_duplicates()`
2. Eliminar caracteres no deseados
`str.replace()`
3. Corrección del tipo de dato
df[ “campo” ].astype(float) [texto del enlace](https://)
4. Manejo de datos faltantes
`dropna()`
`fillna()`
5. Normalización de datos
`.str.strip().lower()`
6. Filtrado de datos
`df [ df[“campo”] + condición ]`

## Importamos algunos datasets para explorar

In [10]:
# Importar la librería Pandas
import pandas as pd

In [60]:
# Montar la unidad
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [13]:
# Verificar que los archivos csv se encuentren en la carpeta datasets
import os
os.listdir("/content/drive/MyDrive/Datasets")

['reviews.csv',
 'Kaggle_users.xlsx',
 'users.csv',
 'hotels.csv',
 'booking_db.sqlite',
 'satis_clientes.csv']

In [15]:
# Importamos el Dataset satis (customer satisfaction)
df_satis = pd.read_csv("/content/drive/MyDrive/Datasets/satis_clientes.csv")
df_satis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1128 entries, 0 to 1127
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            1128 non-null   int64
 1   Empresa       1128 non-null   object
 2   Fecha         1128 non-null   object
 3   Calificación  904 non-null    float64
 4   Comentarios   818 non-null    object
dtypes: float64(1), int64(1), object(3)
memory usage: 44.2+ KB

In [69]:
# Importamos el Dataset Netflix
df_netflix = pd.read_csv("/content/drive/MyDrive/Datasets/netflix_titles.csv")
df_netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [68]:
import os
os.listdir("/content/drive/MyDrive/Datasets")

['reviews.csv',
 'Kaggle_users.xlsx',
 'users.csv',
 'hotels.csv',
 'booking_db.sqlite',
 'satis_clientes.csv',
 'netflix_titles.csv']

In [ ]:
# Importamos el Dataset de pacientes con sus mediciones de temperatura
df_pacientes = pd.read_csv('https://docs.google.com/spreadsheets/d/1-rUn4TUwpGrLE1DH8moeiR5eSyeF-jOOTpfhRgZxVIQ/gviz/tq?tqx=out:csv&sheet=')
df_pacientes.info()

## Identificación de datos duplicados

[duplicated()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.duplicated.html)

### Dataframe satis

In [16]:
df_satis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1128 entries, 0 to 1127
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            1128 non-null   int64
 1   Empresa       1128 non-null   object
 2   Fecha         1128 non-null   object
 3   Calificación  904 non-null    float64
 4   Comentarios   818 non-null    object
dtypes: float64(1), int64(1), object(3)
memory usage: 44.2+ KB

In [17]:
# Veamos si hay duplicados
df_satis.duplicated().sum()

np.int64(128)

In [18]:
# Veamos cuantos registros duplicados hay
df_satis.duplicated(subset=["Empresa", "Calificación"]).sum()

np.int64(134)

In [19]:
# Contar valores unicos
df_satis.value_counts(subset=["Empresa", "Calificación"]).sort_values(ascending=False)

Empresa                       Calificación
Batz-Buckridge                4.0             2
VonRueden-Kerluke             5.0             2
Powlowski-Champlin            1.0             2
Johnson, Hermann and Stark    4.0             2
Johnson Inc                   4.0             2
                                             ..
Swaniawski-Ortiz              1.0             1
Terry Group                   2.0             1
Terry LLC                     3.0             1
Thompson Inc                  3.0             1
Stoltenberg, Sawayn and West  3.0             1
Name: count, Length: 798, dtype: int64

In [20]:
# Visualizar los duplicados con diferentes argumentos
df_satis[df_satis.duplicated(keep=False)].sort_values(by='Empresa')

,id,Empresa,Fecha,Calificación,Comentarios
1122,995,Altenwerth LLC,13/09/2024,NaN,NaN
1121,995,Altenwerth LLC,13/09/2024,NaN,NaN
811,726,"Altenwerth, Blanda and Waelchi",28/09/2024,1.0,"Proin leo odio, porttitor id, consequat in, co..."
812,726,"Altenwerth, Blanda and Waelchi",28/09/2024,1.0,"Proin leo odio, porttitor id, consequat in, co..."
187,172,"Altenwerth, Reichert and Mills",07/08/2024,3.0,"Proin eu mi. Nulla ac enim. In tempor, turpis ..."
...,...,...,...,...,...
469,423,Zemlak Group,13/12/2024,5.0,Duis consequat dui nec nisi volutpat eleifend....
973,865,Zemlak Inc,29/03/2024,3.0,Fusce consequat. Nulla nisl. Nunc nisl.\n\nDui...
974,865,Zemlak Inc,29/03/2024,3.0,Fusce consequat. Nulla nisl. Nunc nisl.\n\nDui...
512,459,Zulauf LLC,29/04/2024,5.0,NaN
511,459,Zulauf LLC,29/04/2024,5.0,NaN

In [21]:
# Aplicar filtros
df_satis[df_satis['Empresa'] == "Keebler Inc"]

,id,Empresa,Fecha,Calificación,Comentarios
4,5,Keebler Inc,12/01/2024,4.0,Integer ac leo. Pellentesque ultrices mattis o...
636,570,Keebler Inc,28/07/2024,5.0,Vestibulum ac est lacinia nisi venenatis trist...

In [22]:
df_satis[df_satis.duplicated(subset=["Empresa", "Fecha"],keep=False)].sort_values(by='id')

,id,Empresa,Fecha,Calificación,Comentarios
9,10,Legros-Olson,12/11/2024,5.0,NaN
10,10,Legros-Olson,12/11/2024,5.0,NaN
11,11,Harris-Davis,13/11/2024,1.0,Nullam sit amet turpis elementum ligula vehicu...
12,11,Harris-Davis,13/11/2024,1.0,Nullam sit amet turpis elementum ligula vehicu...
17,16,"White, Balistreri and Daugherty",29/06/2024,5.0,NaN
...,...,...,...,...,...
1109,984,"Strosin, Raynor and Oberbrunner",14/02/2024,1.0,Morbi porttitor lorem id ligula. Suspendisse o...
1117,992,Donnelly-Bashirian,14/03/2024,NaN,Nullam porttitor lacus at turpis. Donec posuer...
1118,992,Donnelly-Bashirian,14/03/2024,NaN,Nullam porttitor lacus at turpis. Donec posuer...
1121,995,Altenwerth LLC,13/09/2024,NaN,NaN
1122,995,Altenwerth LLC,13/09/2024,NaN,NaN

In [23]:
df_satis[df_satis.duplicated(subset=df_satis.columns[1:],keep=False)].sort_values(by='Empresa')

,id,Empresa,Fecha,Calificación,Comentarios
1122,995,Altenwerth LLC,13/09/2024,NaN,NaN
1121,995,Altenwerth LLC,13/09/2024,NaN,NaN
811,726,"Altenwerth, Blanda and Waelchi",28/09/2024,1.0,"Proin leo odio, porttitor id, consequat in, co..."
812,726,"Altenwerth, Blanda and Waelchi",28/09/2024,1.0,"Proin leo odio, porttitor id, consequat in, co..."
187,172,"Altenwerth, Reichert and Mills",07/08/2024,3.0,"Proin eu mi. Nulla ac enim. In tempor, turpis ..."
...,...,...,...,...,...
469,423,Zemlak Group,13/12/2024,5.0,Duis consequat dui nec nisi volutpat eleifend....
973,865,Zemlak Inc,29/03/2024,3.0,Fusce consequat. Nulla nisl. Nunc nisl.\n\nDui...
974,865,Zemlak Inc,29/03/2024,3.0,Fusce consequat. Nulla nisl. Nunc nisl.\n\nDui...
512,459,Zulauf LLC,29/04/2024,5.0,NaN
511,459,Zulauf LLC,29/04/2024,5.0,NaN

### Dataframe Pacientes

In [ ]:
# Veamos cuantos registros duplicados hay
df_pacientes.duplicated().sum()

In [ ]:
# Si hay, entonces los listamos (keep, first, last, False)
df_pacientes[df_pacientes.duplicated(subset=["nombre"], keep=False)].sort_values(by='nombre')

### Dataframe Netflix

In [70]:
df_netflix.duplicated().sum()

np.int64(0)

In [71]:
df_netflix[df_netflix.duplicated()]

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description]
Index: []

## Tratamiento de datos duplicados
[Pandas drop_duplicates()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop_duplicates.html)

### Dataset Satis

In [24]:
df_satis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1128 entries, 0 to 1127
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            1128 non-null   int64
 1   Empresa       1128 non-null   object
 2   Fecha         1128 non-null   object
 3   Calificación  904 non-null    float64
 4   Comentarios   818 non-null    object
dtypes: float64(1), int64(1), object(3)
memory usage: 44.2+ KB

In [25]:
df_satis_pp1 = df_satis.drop_duplicates(subset=["Empresa", "Calificación"], keep="first")
df_satis_pp1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 994 entries, 0 to 1127
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            994 non-null    int64
 1   Empresa       994 non-null    object
 2   Fecha         994 non-null    object
 3   Calificación  798 non-null    float64
 4   Comentarios   728 non-null    object
dtypes: float64(1), int64(1), object(3)
memory usage: 46.6+ KB

In [ ]:
df_netflix.duplicated().sum()

In [26]:
df_satis_pp1[df_satis_pp1.duplicated(subset=["Empresa", "Calificación"], keep=False)].sort_values(by='Empresa')

Empty DataFrame
Columns: [id, Empresa, Fecha, Calificación, Comentarios]
Index: []

## Exploración de datos nulos

In [27]:
df_satis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1128 entries, 0 to 1127
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            1128 non-null   int64
 1   Empresa       1128 non-null   object
 2   Fecha         1128 non-null   object
 3   Calificación  904 non-null    float64
 4   Comentarios   818 non-null    object
dtypes: float64(1), int64(1), object(3)
memory usage: 44.2+ KB

In [28]:
# Ver si hay valores nulos, en general o en columnas especificas
#df_satis.isnull().sum()
#df_satis[["Comentarios", "Calificación"]].isnull().sum()
df_satis.isnull().any(axis=1).sum()

np.int64(477)

In [29]:
# Visualizar los registros con celdas null / NaN
df_satis[df_satis.isnull().any(axis=1)][["Comentarios", "Calificación"]]

                                            Comentarios  Calificación
3                                                   NaN           1.0
6                                                   NaN           NaN
7     Donec diam neque, vestibulum eget, vulputate u...           NaN
8                                                   NaN           NaN
9                                                   NaN           5.0
...                                                 ...           ...
1121                                                NaN           NaN
1122                                                NaN           NaN
1124  In hac habitasse platea dictumst. Morbi vestib...           NaN
1125                                                NaN           4.0
1127                                                NaN           1.0

[477 rows x 2 columns]

## Tratamiento de datos nulos

### drop

`dropna` se usa para eliminar registros que contengan datos nulos
<BR>
[Pandas dropna](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html)

* how: para especificar si (any / all) celdas deben tener NaN
* thresh: indicar la cantidad de NaN para ejecutar el drop (no se puede combinar con any)
* subset: indicar las columnas a evaluar
* inplace: si guarda los cambios en el dataframe o retorna una copia

Analizar y comparar que sucede cuando aplicamos dropna a todas las columnas o a algunas especificas.

In [30]:
# Eliminar un registro si alguna las columnas contienen NaA
df_satis_pp2 = df_satis.dropna()
df_satis_pp2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 651 entries, 0 to 1126
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            651 non-null    int64
 1   Empresa       651 non-null    object
 2   Fecha         651 non-null    object
 3   Calificación  651 non-null    float64
 4   Comentarios   651 non-null    object
dtypes: float64(1), int64(1), object(3)
memory usage: 30.5+ KB

In [31]:
# Eliminar un registro si alguna o tdas las columnas contienen NaA
df_satis_pp2 = df_satis.dropna(how="all")
df_satis_pp2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1128 entries, 0 to 1127
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            1128 non-null   int64
 1   Empresa       1128 non-null   object
 2   Fecha         1128 non-null   object
 3   Calificación  904 non-null    float64
 4   Comentarios   818 non-null    object
dtypes: float64(1), int64(1), object(3)
memory usage: 44.2+ KB

In [32]:
# Eliminar un registro solo evaluando NaN en las columnas indicadas
df_satis_pp2 = df_satis.dropna(subset=["Comentarios", "Calificación"])
df_satis_pp2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 651 entries, 0 to 1126
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            651 non-null    int64
 1   Empresa       651 non-null    object
 2   Fecha         651 non-null    object
 3   Calificación  651 non-null    float64
 4   Comentarios   651 non-null    object
dtypes: float64(1), int64(1), object(3)
memory usage: 30.5+ KB

In [33]:
# Eliminar una columna si contiene NaN
df_satis_pp2 = df_satis.dropna(axis=1) # no accepta subset
df_satis_pp2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1128 entries, 0 to 1127
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       1128 non-null   int64
 1   Empresa  1128 non-null   object
 2   Fecha    1128 non-null   object
dtypes: int64(1), object(2)
memory usage: 26.6+ KB

### fill

`fillna` se utiliza para completar el dato faltante
<BR>
[Pandas fillna](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html)
<BR>
* df.fillna(0)  se completa con un valor fijo
* df.fillna(method="ffill")  completa con el valor del registro anterior
* df.fillna(method="bfill") completa con el valor del registro previo
* df["col"].fillna(df["col"].mean()) completa con la media de la columna
* df.fillna({"col1": 0, "col2": "desconocido"})

1. completamos con un valor fijo

In [34]:
# usamos el atributo value con un valor fijo en 0
df_satis_pp3 = df_satis.fillna(value = 0)
df_satis_pp3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1128 entries, 0 to 1127
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            1128 non-null   int64
 1   Empresa       1128 non-null   object
 2   Fecha         1128 non-null   object
 3   Calificación  1128 non-null   float64
 4   Comentarios   1128 non-null   object
dtypes: float64(1), int64(1), object(3)
memory usage: 44.2+ KB

In [35]:
# También podríamos usar un diccionario
df_satis_pp3 = df_satis.fillna({"Calificación": 0, "Comentarios": "Sin dato"})

In [36]:
# listamos los primeros registros
df_satis_pp3.head(10)

,id,Empresa,Fecha,Calificación,Comentarios
0,1,Mitchell Group,11/12/2024,1.0,Integer ac leo. Pellentesque ultrices mattis o...
1,2,Kuhn-Fay,25/01/2024,4.0,Vestibulum ac est lacinia nisi venenatis trist...
2,3,Moen-Blick,11/11/2024,3.0,Aliquam quis turpis eget elit sodales sceleris...
3,4,McDermott Inc,01/12/2024,1.0,Sin dato
4,5,Keebler Inc,12/01/2024,4.0,Integer ac leo. Pellentesque ultrices mattis o...
5,6,Dickinson Inc,30/04/2024,1.0,Phasellus in felis. Donec semper sapien a libe...
6,7,Moen-Hartmann,11/03/2024,0.0,Sin dato
7,8,Lubowitz and Sons,27/01/2024,0.0,"Donec diam neque, vestibulum eget, vulputate u..."
8,9,Waters-Lakin,04/09/2024,0.0,Sin dato
9,10,Legros-Olson,12/11/2024,5.0,Sin dato

In [37]:
# Eventualmente ajustamos el tipo de dato
df_satis_pp3 = df_satis_pp3.astype({"Comentarios": "string"})
df_satis_pp3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1128 entries, 0 to 1127
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            1128 non-null   int64
 1   Empresa       1128 non-null   object
 2   Fecha         1128 non-null   object
 3   Calificación  1128 non-null   float64
 4   Comentarios   1128 non-null   string
dtypes: float64(1), int64(1), object(2), string(1)
memory usage: 44.2+ KB

In [38]:
# Podemos aplicar filtros
df_satis_pp3[df_satis_pp3["Comentarios"]=="0"]

Empty DataFrame
Columns: [id, Empresa, Fecha, Calificación, Comentarios]
Index: []

2. Completamos con el valor próximo

In [39]:
df_satis_pp3 = df_satis.fillna(method = "ffill")
df_satis_pp3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1128 entries, 0 to 1127
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            1128 non-null   int64
 1   Empresa       1128 non-null   object
 2   Fecha         1128 non-null   object
 3   Calificación  1128 non-null   float64
 4   Comentarios   1128 non-null   object
dtypes: float64(1), int64(1), object(3)
memory usage: 44.2+ KB

/tmp/ipython-input-2216802605.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_satis_pp3 = df_satis.fillna(method = "ffill")

3. Completamos con el valor previo

In [40]:
df_satis_pp3 = df_satis.fillna(method = "bfill")
df_satis_pp3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1128 entries, 0 to 1127
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            1128 non-null   int64
 1   Empresa       1128 non-null   object
 2   Fecha         1128 non-null   object
 3   Calificación  1128 non-null   float64
 4   Comentarios   1127 non-null   object
dtypes: float64(1), int64(1), object(3)
memory usage: 44.2+ KB

/tmp/ipython-input-948418978.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_satis_pp3 = df_satis.fillna(method = "bfill")

4. Completamos con la media, meadiana, moda

In [41]:
df_satis_pp3 = df_satis.fillna(df_satis.mean(numeric_only=True))
df_satis_pp3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1128 entries, 0 to 1127
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            1128 non-null   int64
 1   Empresa       1128 non-null   object
 2   Fecha         1128 non-null   object
 3   Calificación  1128 non-null   float64
 4   Comentarios   818 non-null    object
dtypes: float64(1), int64(1), object(3)
memory usage: 44.2+ KB

In [42]:
# calcular la media de la columna Calificación
media_calif = df_satis["Calificación"].mode()[0] # mean() / median() / mode()[0]

# aplicar fillna con diccionario
df_satis_pp3 = df_satis.fillna({
    "Calificación": media_calif,
    "Comentarios": "Sin dato"
})

In [43]:
df_satis_pp3.head(5)

,id,Empresa,Fecha,Calificación,Comentarios
0,1,Mitchell Group,11/12/2024,1.0,Integer ac leo. Pellentesque ultrices mattis o...
1,2,Kuhn-Fay,25/01/2024,4.0,Vestibulum ac est lacinia nisi venenatis trist...
2,3,Moen-Blick,11/11/2024,3.0,Aliquam quis turpis eget elit sodales sceleris...
3,4,McDermott Inc,01/12/2024,1.0,Sin dato
4,5,Keebler Inc,12/01/2024,4.0,Integer ac leo. Pellentesque ultrices mattis o...

Analicemos el dataset pacientes

In [44]:
df_pacientes.info()

NameError: name 'df_pacientes' is not defined

In [ ]:
# Completamos con la media de la columna
df_pacientes_pp1 = df_pacientes.fillna(df_pacientes.mean(numeric_only=True))
df_pacientes_pp1.info()

In [ ]:
# Completamos con la media de la fila usando lambda

# seleccionar solo las columnas d1...d10
cols = df_pacientes.columns[1:]   # todas excepto 'nombre'

# aplicar moda por fila
df_pacientes_pp1[cols] = df_pacientes[cols].apply(
    lambda row: row.fillna(row.mean()), axis=1
)

In [ ]:
# Completamos con la media de la fila usando T (traspuesta)
df_pacientes_pp1[cols] = df_pacientes[cols].T.fillna(df_pacientes[cols].mean(axis=1)).T

In [ ]:
#df_pacientes.head()
df_pacientes_pp1.head()

Veamos el concepto de Traspuesta

In [45]:
df = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [4, 5, 6]
})
print("Original:")
print(df)

print("\nTranspuesta:")
print(df.T)

Original:
   A  B
0  1  4
1  2  5
2  3  6

Transpuesta:
   0  1  2
A  1  2  3
B  4  5  6

## Normalización de datos

## Ajustar tipo de dato

### astype()

* df["col"] = df["col"].astype(int)
* df["col"] = df["col"].astype(float)
* df["col"] = df["col"].astype(str)

In [46]:
df_satis_pp4 = df_satis.copy()
df_satis_pp4["Comentarios"] = df_satis["Comentarios"].astype("string")

In [47]:
df_satis_pp4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1128 entries, 0 to 1127
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            1128 non-null   int64
 1   Empresa       1128 non-null   object
 2   Fecha         1128 non-null   object
 3   Calificación  904 non-null    float64
 4   Comentarios   818 non-null    string
dtypes: float64(1), int64(1), object(2), string(1)
memory usage: 44.2+ KB

### to_numeric()

In [48]:
pd.to_numeric(df["col"], errors="coerce")

KeyError: 'col'

### to_datetime()

In [50]:
type(df_satis["Fecha"][0])
df_satis["Fecha"][0]

'11/12/2024'

In [51]:
# pd.to_datetime(df_satis.Fecha)
pd.to_datetime(df_satis["Fecha"], format="%d/%m/%Y")

0      2024-12-11
1      2024-01-25
2      2024-11-11
3      2024-12-01
4      2024-01-12
          ...
1123   2024-04-19
1124   2024-12-25
1125   2024-05-23
1126   2024-11-14
1127   2024-03-30
Name: Fecha, Length: 1128, dtype: datetime64[ns]

## Filtrado de datos

In [49]:
df_satis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1128 entries, 0 to 1127
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            1128 non-null   int64
 1   Empresa       1128 non-null   object
 2   Fecha         1128 non-null   object
 3   Calificación  904 non-null    float64
 4   Comentarios   818 non-null    object
dtypes: float64(1), int64(1), object(3)
memory usage: 44.2+ KB

In [52]:
# Con una sola columna
df_satis["Empresa"]

0                         Mitchell Group
1                               Kuhn-Fay
2                             Moen-Blick
3                          McDermott Inc
4                            Keebler Inc
                      ...
1123                  Schiller-Armstrong
1124     Schimmel, Gleichner and O'Keefe
1125            Strosin, Tromp and Dicki
1126    Schultz, Vandervort and Mosciski
1127       Prohaska, Quitzon and Strosin
Name: Empresa, Length: 1128, dtype: object

In [53]:
# Con varias columnas
df_satis[["Empresa", "Fecha"]]

                               Empresa       Fecha
0                       Mitchell Group  11/12/2024
1                             Kuhn-Fay  25/01/2024
2                           Moen-Blick  11/11/2024
3                        McDermott Inc  01/12/2024
4                          Keebler Inc  12/01/2024
...                                ...         ...
1123                Schiller-Armstrong  19/04/2024
1124   Schimmel, Gleichner and O'Keefe  25/12/2024
1125          Strosin, Tromp and Dicki  23/05/2024
1126  Schultz, Vandervort and Mosciski  14/11/2024
1127     Prohaska, Quitzon and Strosin  30/03/2024

[1128 rows x 2 columns]

In [54]:
df_satis[df_satis["Empresa"] == "Kuhn-Fay"]

,id,Empresa,Fecha,Calificación,Comentarios
1,2,Kuhn-Fay,25/01/2024,4.0,Vestibulum ac est lacinia nisi venenatis trist...

In [56]:
# Con condición
df_satis[(df_satis["Empresa"] =="Alpha") & (df_satis["Calificación"] > 3)]

Empty DataFrame
Columns: [id, Empresa, Fecha, Calificación, Comentarios]
Index: []